### ISSUE TITLE
v-tooltip directive creates multiple App instances

### ISSUE THREAD

**Issue by 0x0dr1y** [mtorromeo/vue-patternfly3#37]
Hey there :) 

It seems like the v-tooltip directive is causing several app instances when it's used. As far as i understood the usage of `createApp` is the cause of this. I sadly don't have any good alternative in my mind without refactoring the whole directive. Maybe you have one :)

**Comment by mtorromeo** [comment]
Yes, this is expected, though they should also be freed when the tooltips are "unmounted".

This was the only straightforward way to port it to Vue 3 without reimplementing them altogether.

A more lightweight approach would be using the Tooltip component instead of the directive. In fact, I did not implement a similar directive in vue-patternfly4 for this reason.

**Comment by 0x0dr1y** [comment]
Fair enough! Sadly this causes **several thousand** instances for me, which seems to be causing a very poor performance. I'll see if i can come up with a better solution without the additional instances on the weekend, so that you can focus on vue-patternfly4 (I'm looking forward to contribute once i'm done migrating my app). If i cannot find a good approach i might just switch to another solution like  https://github.com/Akryum/v-tooltip (maybe something for vue-patternfly4), so that there is no need to spend additional time for this project.

**Comment by mtorromeo** [comment]
That library might be a good solution. I already have my own implementation of tooltips and popovers using popper.js in pf4, just not the directives. I might replace it with that library when a stable version for vue 3 comes out.

I wonder though, what would be the performance difference with your use case of having several thousand tooltips since it will instantiate thousands of custom classes instead of vue apps, and it might end up perform similarly (I still expect it to perform better honestly).

I am interested in your experience if you end up testing it.

**Comment by 0x0dr1y** [comment]
Hey, long time no see :)

I actually had time and enough reasons to dig into it. I've found an issue with abandoned nodes caused by a failing cleanup. See https://github.com/mtorromeo/vue-patternfly3/pull/46 for details.

Cheers! :)
